const DocumentType = {
    BIRTH_CERTIFICATE: 'BIRTH_CERTIFICATE',
    PASSPORT: 'PASSPORT',
    DRIVING_LICENSE: 'DRIVING_LICENSE',
    NATIONAL_ID: 'NATIONAL_ID',
    VOTER_ID: 'VOTER_ID',
    PAN_CARD: 'PAN_CARD',
    AADHAR_CARD: 'AADHAR_CARD',
    RATION_CARD: 'RATION_CARD',
    BANK_PASSBOOK: 'BANK_PASSBOOK',
    STUDENT_ID: 'STUDENT_ID',
    EMPLOYEE_ID: 'EMPLOYEE_ID',
    OTHERS: 'OTHERS'
}

export default DocumentType;