const PositionType = {
    ADMIN: 'ADMIN',
    HR: 'HR',
    MANAGER: 'MANAGER',
    DEVELOPER: 'DEVELOPER',
    DESIGNER: 'DESIGNER',
    TESTER: 'TESTER',
    ACCOUNTANT: 'ACCOUNTANT',
    MARKETING: 'MARKETING',
    SALES: 'SALES',
    CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
    PRODUCT: 'PRODUCT',
    OTHERS: 'OTHERS',
};

export default PositionType;